force-app/main/default/objects/CaseParticipant__c/CaseParticipant__c.object-meta.xml
<CustomObject>
    <description>Represents a user involved in a Case and defines their level of interaction. Record changes in this object trigger the dynamic sharing engine to calculate and grant the appropriate Case access based on the participant&apos;s role.</description>
    <label>Case Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseParticipant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>The Case associated with this participant. The sharing engine uses this reference to create or update the appropriate sharing records (CaseShare) for the target Case</description>
    <inlineHelpText>The Case associated with this participant. The sharing engine uses this reference to create or update the appropriate sharing records (CaseShare) for the target Case</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Participants</relationshipLabel>
    <relationshipName>CaseParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseParticipant__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <defaultValue>&apos;Viewer&apos;</defaultValue>
    <description>Defines the participant&apos;s responsibility and access level for the related Case (e.g., Manager, Editor, Viewer). This value is evaluated by the sharing engine to determine if the user receives Read or Read/Write access</description>
    <inlineHelpText>Defines the participant&apos;s responsibility and access level for the related Case (e.g., Manager, Editor, Viewer). This value is evaluated by the sharing engine to determine if the user receives Read or Read/Write access</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Viewer</fullName>
            </value>
            <value>
                <fullName>Editor</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseParticipant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The internal Salesforce User acting as a participant. The sharing engine uses this field to identify which user will receive access to the related Case.</description>
    <inlineHelpText>The internal Salesforce User acting as a participant. The sharing engine uses this field to identify which user will receive access to the related Case.</inlineHelpText>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CaseParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseParticipantDeleteSharingService.cls
public with sharing class CaseParticipantDeleteSharingService implements RecordSharingService.ISharingHandler {

    //
    // RecordSharingService.ISharingHandler methods
    //

    public void executeSharing(List<CaseShare> recordShares) {

        Map<String, CaseParticipant__c> caseParticipantByExternalId = new Map<String, CaseParticipant__c>();
        Set<String> caseIds = new Set<String>();
        Set<String> userIds = new Set<String>();

        // Mapeia Case Shares dos Case Participants que foram removidos
        for (CaseShare recordShare : recordShares) {
            caseIds.add(recordShare.CaseId);
            userIds.add(recordShare.UserOrGroupId);
        }

        List<CaseParticipant__c> caseParticipants = [
            SELECT Id, Case__c, User__c, Role__c 
            FROM CaseParticipant__c 
            WHERE Case__c IN :caseIds AND User__c IN :userIds
        ];

        // Mapeia Case Participants existentes (que não foram removidos)
        for (CaseParticipant__c caseParticipant : caseParticipants) {
            String accessLevel = caseParticipant.Role__c == 'Viewer' ? 'Read' : 'Edit';

            caseParticipantByExternalId.put(
                caseParticipant.Case__c + '|' + caseParticipant.User__c + '|' + accessLevel, caseParticipant
            );
        }

        List<CaseShare> caseShareToDelete = new List<CaseShare>();
        for (CaseShare recordShare : recordShares) {
            String matchId = recordShare.CaseId + '|' + recordShare.UserOrGroupId + '|' + recordShare.CaseAccessLevel;

            if (!caseParticipantByExternalId.containsKey(matchId)) {
                caseShareToDelete.add(recordShare);
                caseParticipantByExternalId.remove(matchId);
            }            
        }

        Database.DeleteResult[] deleteResults = Database.delete(caseShareToDelete, false, AccessLevel.SYSTEM_MODE);
        String errorMessage = '';
        for (Database.DeleteResult deleteResult : deleteResults) {
            if (!deleteResult.isSuccess()) {
                for (Database.Error error : deleteResult.getErrors()) {
                    errorMessage += error.getStatusCode() + ': ' + error.getMessage() + '\n';
                }
            }
        }

        if (!String.isBlank(errorMessage)) { System.debug('Errors during case sharing deletion: \n' + errorMessage); }

        // If any records remain with access, but their major access level has been removed, reprocess
        
        if (!caseParticipantByExternalId.isEmpty()) {
            new CaseParticipantUpdateSharingService().executeSharing(caseParticipantByExternalId.values());
        }
    }
}