force-app/main/default/objects/CaseParticipant__c/CaseParticipant__c.object-meta.xml
<CustomObject>
    <description>Represents a user involved in a Case and defines their level of interaction. Record changes in this object trigger the dynamic sharing engine to calculate and grant the appropriate Case access based on the participant&apos;s role.</description>
    <label>Case Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseParticipant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>The Case associated with this participant. The sharing engine uses this reference to create or update the appropriate sharing records (CaseShare) for the target Case</description>
    <inlineHelpText>The Case associated with this participant. The sharing engine uses this reference to create or update the appropriate sharing records (CaseShare) for the target Case</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Participants</relationshipLabel>
    <relationshipName>CaseParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseParticipant__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <defaultValue>&apos;Viewer&apos;</defaultValue>
    <description>Defines the participant&apos;s responsibility and access level for the related Case (e.g., Manager, Editor, Viewer). This value is evaluated by the sharing engine to determine if the user receives Read or Read/Write access</description>
    <inlineHelpText>Defines the participant&apos;s responsibility and access level for the related Case (e.g., Manager, Editor, Viewer). This value is evaluated by the sharing engine to determine if the user receives Read or Read/Write access</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Viewer</fullName>
            </value>
            <value>
                <fullName>Editor</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseParticipant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The internal Salesforce User acting as a participant. The sharing engine uses this field to identify which user will receive access to the related Case.</description>
    <inlineHelpText>The internal Salesforce User acting as a participant. The sharing engine uses this field to identify which user will receive access to the related Case.</inlineHelpText>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CaseParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseParticipantSharingService.cls
public without sharing class CaseParticipantSharingService implements RecordSharingService.ISharingHandler {
    
    //
    // RecordSharingService.ISharingHandler methods
    //

    public void executeSharing(List<CaseParticipant__c> records, String operationType) {
        switch on operationType {
            when  'AFTER_DELETE' {
                deleteSharing(records);
            }
            when 'AFTER_INSERT', 'AFTER_UPDATE' {
                updateSharing(records);
            }
        }
    }

    //
    // Auxiliar Methods
    //

    private void deleteSharing(List<CaseParticipant__c> recordsDeletedSharing) {
        Set<String> viewAccessCaseIds = new Set<String>();
        Set<String> viewAccessUserOrGroupIds = new Set<String>();
        Set<String> editAccessCaseIds = new Set<String>();
        Set<String> editAccessUserOrGroupIds = new Set<String>();

        for (CaseParticipant__c caseParticipant : recordsDeletedSharing) {
            switch on caseParticipant.Role__c {
                when 'Viewer' {
                    viewAccessCaseIds.add(caseParticipant.Case__c);
                    viewAccessUserOrGroupIds.add(caseParticipant.User__c);
                }
                when 'Editor', 'Manager' {
                    editAccessCaseIds.add(caseParticipant.Case__c);
                    editAccessUserOrGroupIds.add(caseParticipant.User__c);
                }
            }
        }

        List<CaseShare> existingSharingViewer = [
            SELECT Id 
            FROM CaseShare 
            WHERE CaseId IN :viewAccessCaseIds 
            AND UserOrGroupId IN :viewAccessUserOrGroupIds 
            AND CaseAccessLevel = 'Read'
            AND RowCause = 'Manual'
        ];

        List<CaseShare> existingSharingEditorOrManager = [
            SELECT Id 
            FROM CaseShare 
            WHERE CaseId IN :editAccessCaseIds 
            AND UserOrGroupId IN :editAccessUserOrGroupIds 
            AND CaseAccessLevel = 'Edit'
            AND RowCause = 'Manual'
        ];

        List<CaseShare> recordsToDelete = new List<CaseShare>();
        recordsToDelete.addAll(existingSharingViewer);
        recordsToDelete.addAll(existingSharingEditorOrManager);

        Database.DeleteResult[] deleteResults = Database.delete(recordsToDelete, false, AccessLevel.SYSTEM_MODE);
        String errorMessage = '';
        for (Database.DeleteResult deleteResult : deleteResults) {
            if (!deleteResult.isSuccess()) {
                for (Database.Error error : deleteResult.getErrors()) {
                    errorMessage += error.getStatusCode() + ': ' + error.getMessage() + '\n';
                }
            }
        }

        if (!String.isBlank(errorMessage)) { System.debug('Errors during case sharing deletion: \n' + errorMessage); }
    }

    private void updateSharing(List<CaseParticipant__c> recordsUpdatedSharing) {
        List<CaseShare> newSharing = new List<CaseShare>();

        for (CaseParticipant__c caseParticipant : recordsUpdatedSharing) {
            newSharing.add(
                new CaseShare(
                    RowCause = 'Manual',
                    CaseAccessLevel = caseParticipant.Role__c == 'Viewer' ? 'Read' : 'Edit',
                    CaseId = caseParticipant.Case__c,
                    UserOrGroupId = caseParticipant.User__c
                )
            );
        }

        Database.SaveResult[] saveResults = Database.insert(newSharing, false, AccessLevel.SYSTEM_MODE);
        String errorMessage = '';
        for (Database.SaveResult saveResult : saveResults) {
            if (!saveResult.isSuccess()) {
                for (Database.Error error : saveResult.getErrors()) {
                    errorMessage += error.getStatusCode() + ': ' + error.getMessage() + '\n';
                }
            }
        }

        if (!String.isBlank(errorMessage)) { System.debug('Errors during case sharing update: \n' + errorMessage); }
    }
}