force-app/main/default/objects/CaseParticipant__c/CaseParticipant__c.object-meta.xml
<CustomObject>
    <description>Represents a user involved in a Case and defines their level of interaction. Record changes in this object trigger the dynamic sharing engine to calculate and grant the appropriate Case access based on the participant&apos;s role.</description>
    <label>Case Participant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseParticipant__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>The Case associated with this participant. The sharing engine uses this reference to create or update the appropriate sharing records (CaseShare) for the target Case</description>
    <inlineHelpText>The Case associated with this participant. The sharing engine uses this reference to create or update the appropriate sharing records (CaseShare) for the target Case</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Participants</relationshipLabel>
    <relationshipName>CaseParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseParticipant__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The internal Salesforce User acting as a participant. The sharing engine uses this field to identify which user will receive access to the related Case.</description>
    <inlineHelpText>The internal Salesforce User acting as a participant. The sharing engine uses this field to identify which user will receive access to the related Case.</inlineHelpText>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CaseParticipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseParticipantDeleteSharingQueueable.cls
public with sharing class CaseParticipantDeleteSharingQueueable implements RecordSharingService.ISharingHandler, System.Queueable {
    private Database.Cursor locator;
    private Integer position;
    
    //
    // RecordSharingService.ISharingHandler methods
    //

    public void executeSharing(List<SObject> records) {
        Set<String> caseIds = new Set<String>();
        Set<String> userIds = new Set<String>();

        for (CaseParticipant__c caseParticipant : (List<CaseParticipant__c>) records) {
            caseIds.add(caseParticipant.Case__c);
            userIds.add(caseParticipant.User__c);
        }

        locator = Database.getCursorWithBinds(
            'SELECT Id, CaseId, UserOrGroupId, RowCause, CaseAccessLevel FROM CaseShare WHERE RowCause = \'Manual\' AND CaseId IN :caseIds AND UserOrGroupId IN :userIds', 
            new Map<String, Object> {
                'caseIds' => caseIds,
                'userIds' => userIds
            },
            AccessLevel.SYSTEM_MODE
        );
        position = 0;
        System.enqueueJob(this);
    }


    //
    // Queueable Methods
    //

    public void execute(QueueableContext context) {
        Integer remainingRows = locator.getNumRecords() - position;
        if (remainingRows == 0) {
            return; // Nothing to do
        }

        // Take the minimum of batch size and remaining rows to avoid over-fetching
        List<CaseShare> scope = locator.fetch(position, Math.min(200, remainingRows));
        System.debug('Execution scope: '+scope);
        position += scope.size();
        
        // Do manual sharing
        new CaseParticipantDeleteSharingService().executeSharing(scope);
        
        if (position != 0 && position < locator.getNumRecords()) {
            // process the next chunk
            System.enqueueJob(this);
        }
    }
}